boardgame/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boardgame.views.home', name='home'),
    # url(r'^boardgame/', include('boardgame.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
	url(r'^gamestats/', include('gamestats.urls')),
)

gamestats/urls.py
from django.conf.urls import patterns, url, include
from gamestats.views import general_views, player_views, json_views
from django.views.static import * 
from django.conf import settings

player_patterns = [
	url(r'^$', player_views.player, name='player'),
	url(r'^plays$', player_views.player_plays, name='player_plays'),
	url(r'^wins$', player_views.player_wins, name='player_wins'),
	url(r'^owned$', player_views.player_owned, name='player_owned'),
	url(r'^mechanics$', player_views.player_mechanics, name='player_mechanics'),
	url(r'^mechanics/(?P<mechanic_id>\d+)/wins/$', player_views.player_mechanics_game_wins,
		 name='player_mechanics_game_wins'),
	url(r'^mechanics/(?P<mechanic_id>\d+)/plays/$', player_views.player_mechanics_game_plays,
		 name='player_mechanics_game_plays'),
	url(r'^categories$', player_views.player_categories, name='player_categories'),
	url(r'^categories/(?P<category_id>\d+)/wins/$', player_views.player_categories_game_wins,
		 name='player_categories_game_wins'),
	url(r'^categories/(?P<category_id>\d+)/plays/$', player_views.player_categories_game_plays,
		 name='player_categories_game_plays'),
	url(r'^played-games$', player_views.player_played_games, name='player_played_games'),
]

urlpatterns = patterns('',
	url(r'^bggapi/(?P<game_id>\d+)/$', general_views.bggapi, name='bggapi'),
	url(r'^game/(?P<game_id>\d+)/$', general_views.game, name='game'),
	url(r'^player/(?P<player_id>\d+)/', include(player_patterns)),
	url(r'^play/(?P<play_id>\d+)/$', general_views.play, name='play'),
	url(r'^play/add/$', general_views.add_play, name='add_play'),
	url(r'^main/$', general_views.main, name='main'),
	url(r'^all/(?P<content_type>\w+)/$', general_views.all_content, name='all_content'),
  url(r'^api/play_stats/(?P<metric>\w+)/$', json_views.play_stats_by_month, name='play_stats_by_month'),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

gamestats/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime 



# Create your models here.
class Mechanic(models.Model):
  name = models.CharField(max_length=250, unique=True)
  description = models.TextField()

  def __str__(self): 

    return self.name 

  class Meta: 

    ordering = ['name'] 

  class Admin: 

    pass

class Stat(models.Model):
  name = models.CharField(max_length=100, unique=True)
  description = models.TextField()
  values = models.ManyToManyField('Value', null=True, blank=True)

  def __str__(self): 
    return self.name 

  class Meta: 
    ordering = ['name'] 

  class Admin: 
    pass

class Value(models.Model):
  name = models.CharField(max_length=100, unique=True)
  description = models.TextField()

  def __str__(self): 
    return self.name 

  class Meta: 
    ordering = ['name'] 

  class Admin: 
    pass

class Category(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField()
  
  class Meta: 
    ordering = ['name'] 
    
  def __str__(self): 
    return self.name

  class Admin: 
    pass

class Game(models.Model): 
  bgg_id = models.IntegerField()
  name = models.CharField(max_length=250, unique=True) 
  min_players = models.IntegerField(default=2)
  max_players = models.IntegerField(default=2)
  bgg_playing_time = models.IntegerField(default=2)
  bgg_bayesaverage = models.DecimalField(max_digits=3, decimal_places=2)
  description = models.TextField()
  image = models.CharField(max_length=250, blank=True, null=True)
  weight = models.DecimalField(max_digits=5, decimal_places=4)
  added = models.DateTimeField(default=datetime.datetime.now) 
  expands = models.ForeignKey('self', null=True, blank=True, default=None, related_name="Expansions")
  categories = models.ManyToManyField(Category)
  mechanics = models.ManyToManyField(Mechanic)
  owners = models.ManyToManyField(User)
  Playerstats = models.ManyToManyField(Stat, null=True, blank=True)
  Gamestats = models.ManyToManyField(Stat, null=True, blank=True, related_name="Gamestats")
  
  def get_avg_playtime(self):
    plays = Play.objects.filter(game=self)
    count = len(plays)
    sum = 0
    for play in plays:
      sum += play.play_time
    if count > 0:
      return (sum/count)
    else:
		return (0)

  def __str__(self): 

    return self.name 

    #Overriding
  def save(self, *args, **kwargs):
    import urllib2, urllib, xml.etree.ElementTree as ET, socket
    response = urllib2.urlopen(r'http://www.boardgamegeek.com/xmlapi2/thing?stats=1&id=' + str(self.bgg_id))
    root = ET.fromstring(response.read())
    thumbnail = "http://"+root[0].find("thumbnail").text.split("//")[1]
    image = "http://"+root[0].find("image").text.split("//")[1]
    if socket.gethostname() != 'web352.webfaction.com':
      urllib.urlretrieve(thumbnail, filename="/home/matt/board-game-site/gamestats/static/media/bg_thumbs/"+str(self.bgg_id)+".jpg")
      urllib.urlretrieve(image, filename="/home/matt/board-game-site/gamestats/static/media/bg_images/"+str(self.bgg_id)+".jpg")
    else:
      urllib.urlretrieve(thumbnail, filename="/home/matty348/webapps/static/media/bg_thumbs/"+str(self.bgg_id)+".jpg")
      urllib.urlretrieve(image, filename="/home/matty348/webapps/static/media/bg_images/"+str(self.bgg_id)+".jpg")
    super(Game, self).save(*args, **kwargs)

  class Meta: 

    ordering = ['name'] 

  class Admin: 

    pass


class Play(models.Model):
  game = models.ForeignKey(Game)
  play_image = models.FileField(null=True, blank=True, upload_to='play_images/%Y/%m/%d')
  date = models.DateField(default=datetime.date.today)
  play_time = models.IntegerField()
  num_players = models.IntegerField()
  use_for_stats = models.BooleanField()
  expansions = models.ManyToManyField(Game, null=True, blank=True, related_name="Play Expansions")
  
  def __str__(self): 
    return str(self.id)

  class Admin: 
    pass

class Playstat(models.Model):
  stat = models.ForeignKey(Stat)
  play = models.ForeignKey(Play)
  player = models.ForeignKey(User)
  value = models.CharField(max_length=255)
    
  def __str__(self): 
    return str(self.id)

  class Admin: 
    pass
  

gamestats/views/general_views.py
from django.http import HttpResponseRedirect, HttpResponse
import urllib
import urllib2
import datetime
import os
from gamestats.models import Game, Play, Playstat, Stat, Mechanic, Category
from django.template import Context, RequestContext, Template
from django.shortcuts import  redirect, get_object_or_404 #render_to_response,
from django.core.urlresolvers import reverse
from gamestats.forms import play_form, playstat_form, play_info_form
from django.forms.models import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from jinja2 import FileSystemLoader, Environment
from django.conf import settings
from django.db.models import Q,Avg,Count,Sum
from django.db import connections
from django.shortcuts import render
from django import forms
from gamestats.views.helpers import render_page, get_mechanic_wins_list, get_category_wins_list

# constants
GAME_PLAYER_ID = 2#the id of the player for recording game stats this id set in fixtures.


# VIEWS
#######################################
def bggapi(request, game_id):
	id = game_id
	response = urllib2.urlopen(r'http://www.boardgamegeek.com/xmlapi2/thing?stats=1&id=' + id)
	return HttpResponse(content=response.read(), content_type='application/xml')

#TODO stats for each game
def game(request, game_id):
	game = Game.objects.get(pk=game_id)
	plays = Play.objects.filter(Q(game=game) | Q(expansions__id = game.id))
	avg_playtime =plays.aggregate(Avg('play_time'))
	players_who_have_played = User.objects.filter(id__in=Playstat.objects.filter(play__in=Play.objects.filter(game=game)).values("player"))
	template_names = ['games/' + game_id + '.jinja', 'game_base.jinja']
	variables = {
		'game':game,
		'plays':plays,
		'players_who_have_played':players_who_have_played,
		'avg_playtime':avg_playtime
		}
	return render_page(variables, template_names, request)

def all_content(request, content_type):
	if content_type == 'games':
		content = Game.objects.order_by('name')
	elif content_type == 'plays':
		content = Play.objects.all().order_by('-date')
	elif content_type == 'players':
		content = User.objects.all().order_by('username')
	template_names = ['all.jinja']
	variables = {
		'content_type': content_type,
		'content': content,
		'plays': Play.objects.all(),
	}
	return render_page(variables, template_names, request)


def play(request, play_id):
	play = Play.objects.get(pk=play_id)
	gamestats = Playstat.objects.filter(play=play, player__id = GAME_PLAYER_ID)
	playerstats = Playstat.objects.filter(Q(play=play) & ~Q(player__id = GAME_PLAYER_ID))
	players = User.objects.filter(id__in=playerstats.values('player_id'))
	winner_id = Playstat.objects.filter(play=play, stat__name="won", value="T")[0]
	
	template_names = ['play.jinja']
	variables = {
		'play': play,
		'players':players.order_by('username'),
		'playerstats':playerstats,
		'gamestats':gamestats,
		'winner':winner_id,
	}
	return render_page(variables, template_names, request)

def main(request):
	games = Game.objects.order_by('name')
	plays = Play.objects.order_by('-date')
	players = User.objects.order_by('username').exclude(username="game")
	playstats = plays[0].playstat_set.filter(stat__name='Won')
	avg_playtime = Play.objects.all().aggregate(Avg('play_time'))
	template_names = ['main.jinja']
	variables = {
		'games': games,
		'plays': plays,
		'playstats': playstats,
		'players': players,
		'avg_playtime': avg_playtime,
	}
	return render_page(variables, template_names, request)
	
@staff_member_required
@login_required
def add_play(request):
	#show initial form to get number of players and game so we know how many playstats to have
	if request.method == 'GET':
		form = play_info_form()
		variables = {'play_form': form}
		template_names = ['add_play_1.jinja']
		return render_page(variables, template_names, request)
	
	#means we came from the  initial form. Build and show second form that gets game data
	else:
		players = request.POST.getlist("players")
		game_id = request.POST.get("game")
		print game_id
		playerstats = Game.objects.get(id=game_id).Playerstats.all()
		gamestats = Game.objects.get(id=game_id).Gamestats.all()
		num_stats = len(players) * len(playerstats)
		#an object for inline forms in this case playstat forms
		playstat_formset = inlineformset_factory(Play, Playstat, extra = num_stats, can_delete=False)
		game_formset = inlineformset_factory(Play, Playstat, extra = len(gamestats), can_delete=False)

		
		#set defaults that we just asked for
		form = play_form(initial={'num_players': len(players), 'game': game_id, 'expansions': request.POST.getlist("expansions")}) 
		form.fields['num_players'].widget.attrs['readonly'] = "True"
		form.fields['game'].widget.attrs['readonly'] = "True"
		form.fields['expansions'].widget.attrs['readonly'] = "True"
		
		game_values = []
		for stat in gamestats:
			game_values.append({"stat":stat.id,"player": "2"})
			
		gamestat_forms = game_formset(initial=game_values, prefix='game')
		for f in gamestat_forms:
			f.fields['player'].widget.attrs['hidden'] = "True"
			f.fields['stat'].widget.attrs['hidden'] = "True"
			val_type = Stat.objects.get(id=f.initial["stat"]).values.first().name
			if val_type == "boolean":
				f.fields['value'] = forms.ChoiceField(widget=forms.Select, choices=(('F', 'False',), ('T', 'True',)))
			elif val_type == "#":
				f.fields['value'] = forms.ChoiceField(widget=forms.NumberInput)
			else:
				f.fields['value'] = forms.ModelChoiceField(queryset=Stat.objects.get
					(id=f.initial["stat"]).values.all(), to_field_name="name")
			
		values = []	#default values for playerstats
		for stat in playerstats:
			for player in players:
				values.append({"stat":stat.id,"player": player})
				
		playstat_forms = playstat_formset(initial=values, prefix='player')
		
		for count,f in enumerate(playstat_forms):
			f.fields['player'].widget.attrs['hidden'] = "True"
			f.fields['stat'].widget.attrs['hidden'] = "True"
			val_type = Stat.objects.get(id=values[count]["stat"]).values.first().name
			#change value fields based on content
			if val_type == "boolean":
				f.fields['value'] = forms.ChoiceField(widget=forms.Select, choices=(('F', 'False',), ('T', 'True',)))
			elif val_type == "#":
				f.fields['value'] = forms.ChoiceField(widget=forms.NumberInput)
			else:
				f.fields['value'] = forms.ModelChoiceField(queryset=Stat.objects.get(id=values[count]["stat"]).values.all(), to_field_name="name")
		if 'first' in request.POST:		
			template_names = ['add_play_2.jinja']
			variables = {
				'play_form': form,
				'playstat_forms': playstat_forms, 
				'game_form': gamestat_forms,
				'players': players,
				'playerstats': playerstats, 
				'gamestats': gamestats,
				'User': User}
			return render_page(variables, template_names, request)
		else:
			form = play_form(request.POST or None, request.FILES or None)
			if form.is_valid():
				gameformset = game_formset(request.POST, prefix="game")
				playerformset = playstat_formset(request.POST, prefix="player")
				if all([psf.is_valid() for psf in gameformset]) and all([psf.is_valid() for psf in gameformset]):
					new_play = form.save()
					for psf in gameformset:
						new_playstat = psf.save(commit=False)
						new_playstat.play = new_play
						new_playstat.save()
					for psf in playerformset:
						new_playstat = psf.save(commit=False)
						new_playstat.play = new_play
						new_playstat.save()
			else:
				template_names = ['add_play_2.jinja']
				variables = {
					'play_form': form,
					'playstat_forms': playstat_forms, 
					'game_form': gamestat_forms
					}
				return render_page(variables, template_names, request)
			return HttpResponseRedirect('')

gamestats/views/helpers.py
from django.template import RequestContext, loader
from django.http import HttpResponse
from gamestats.models import Play, Mechanic, Category


### Helper Functions////////////////////////

def render_page(variables, template_name_list, request):
	#loading template names as a list allows for fallback templates if the first
	#in the list does not exist this is especially useful for games where they may
	#or may not have a custom page
	template = loader.select_template(template_name_list)
	context = RequestContext(request, variables)
	return HttpResponse(template.render(context))

def get_mechanic_wins_list(user):
	mechanic_wins_list = []
	for mechanic in Mechanic.objects.all():
		mechanic_wins = len(Play.objects.filter(playstat__player=user, playstat__value="T", playstat__stat__name="won", game__mechanics=mechanic))
		mechanic_plays = len(Play.objects.filter(playstat__player=user, playstat__stat__name="won", game__mechanics=mechanic))
		if mechanic_plays > 0:
				mechanic_wins_list.append({'name': mechanic.name, 'id': mechanic.id, 'wins': mechanic_wins, 'plays': mechanic_plays})
	return mechanic_wins_list

def get_category_wins_list(user):
	category_wins_list = []
	for category in Category.objects.all():
		category_wins = len(Play.objects.filter(playstat__player=user, playstat__value="T", playstat__stat__name="won", game__categories=category))
		category_plays = len(Play.objects.filter(playstat__player=user, playstat__stat__name="won", game__categories=category))
		if category_plays > 0:
				category_wins_list.append({'name': category.name, 'id': category.id, 'wins': category_wins, 'plays': category_plays})
	return category_wins_list

gamestats/views/json_views.py
from gamestats.models import Game, Play, Playstat, Stat, Mechanic, Category
from django.db.models import Q,Avg,Count,Sum
from django.db import connections
from django.http import JsonResponse
from gamestats.views.helpers import render_page, get_mechanic_wins_list, get_category_wins_list

def play_stats_by_month(request, metric):
  data = Play.objects.all().order_by('month')
  if metric == 'plays':
    data = Play.objects.all().order_by('month') \
        .extra(select={'month': connections[Play.objects.db].ops.date_trunc_sql('month', 'date')}) \
        .values('month') \
        .annotate(stat=Count('id'))
  elif metric == 'time':
    data = Play.objects.all().order_by('month') \
        .extra(select={'month': connections[Play.objects.db].ops.date_trunc_sql('month', 'date')}) \
        .values('month') \
        .annotate(stat=Sum('play_time'))
  elif metric == 'players':
    data = Play.objects.all().order_by('month') \
        .extra(select={'month': connections[Play.objects.db].ops.date_trunc_sql('month', 'date')}) \
        .values('month') \
        .annotate(stat=Avg('num_players'))
  else:
    data = Play.objects.all().order_by('month') \
        .extra(select={'month': connections[Play.objects.db].ops.date_trunc_sql('month', 'date')}) \
        .values('month') \
        .annotate(plays=Count('id'), time=Sum('play_time'), players=Avg('num_players'))
  return JsonResponse(list(data), safe=False)

gamestats/templates/add_play_1.jinja
{% extends "base.jinja" %}
{% set page_name = "add_play" %}

{% block js %}
	<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<h1>Add Play</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form id="form" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ play_form.as_p() }}
		<input hidden="True" id="id_referer" name="first" type="text" value="first" />
		<input id = "save" type="submit" value="Save"/>
	</form>
{% endblock %}

gamestats/templates/add_play_2.jinja
{% extends "base.jinja" %}
{% set page_name = "add_play" %}

{% block js %}
	<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<h1>Add Play</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form id="form" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		
		{{ play_form.as_p() }}
		
		{# game stat table begins here#}
		{{ game_form.management_form|safe }}
		<h2>Game Stats</h2>
		<table>
			<tr>
				<th/>
				{% for stat in gamestats %}
					<th>{{ stat }}</th>
				{% endfor %}
			</tr>
			<tr>
				<td>Value</td>
				{% for stat in gamestats %}
					<td>
					{% for form in game_form %}
						{% for field in form %}
							{% if field.form.initial["stat"] == stat.id %}
								{{ field|safe }}
							{% endif %}
						{% endfor %}
					{% endfor %}
					</td>
				{% endfor %}
			</tr>
		</table>
		{# game stat table ends here#}
		
		{# playerstats table is below #}
		<h2> Player Stats</h2>
		{{ playstat_forms.management_form|safe }}
		<table>
		<tr>
			<th/>
			{% for player in players %}
				<th>{{ User.objects.get(id=player) }}</th>
			{% endfor %}
		</tr>
		{% for stat in playerstats %}
			<tr>
				<td>
					{{ stat.name }}
				</td>
				{% for player in players %}
					<td>
					{% for form in playstat_forms %}
						{% for field in form %}
							{% if field.form.initial["player"] == player and field.form.initial["stat"] == stat.id %}
								{{ field|safe }}
							{% endif %}
						{% endfor %}
					{% endfor %}
					</td>
				{% endfor %}
			</tr>
		{% endfor %}
		</table>
		<input hidden="True" id="id_referer" name="players" type="text" value="{{ players }}" />
		<input id = "save" type="submit" value="Save"/>
	</form>

{% endblock %}

gamestats/templates/all.jinja
{% extends "base.jinja" %}
{% block title %}All Games{% endblock %}
{% block css %}main.css{% endblock %}
{% block extraHead %}
	<script type="text/javascript" src="{{ static('javascript/sortable.min.js') }}"></script> 
{% endblock %}

{% if content_type == "games" %}
	{% set page_name = "games" %}
{% endif %}
{% if content_type == "plays" %}
	{% set page_name = "plays" %}
{% endif %}
{% if content_type == "players" %}
	{% set page_name = "players" %}
{% endif %}

{% block content %}
	<div class="page-title grid-100">
		<h2>All {{ content_type|title }}</h2>
	</div>
	
	<div class="grid-100">
		<table data-sortable>
			{% if content_type == "games" %}
			<thead>
				<tr>
					<th data-sorted="true" data-sorted-direction="ascending">Name</th>
					<th>BGG Rating</th>
					<th data-sortable="false">Categories</th>
					<th>Min Players</th>
					<th>Max Players</th>
					<th>Total Plays</th>
					<th width="16%">Average Play Time</th>
				</tr>
			</thead>
			<tbody>
				{% for game in content %}
					<tr>
						<td><a href="{{ url('game', game_id=game.id) }}">{{ game.name }}</a></td>
						<td>
							{{ game.bgg_bayesaverage }}
						</td>
						<td>
							{{ game.categories.all()|join(', ') }}
						</td>
						<td>
							{{ game.min_players }}
						</td>
						<td>
							{{ game.max_players }}
						</td>
						<td>{{ game.play_set.count() }}</td>
						<td data-value="{{ game.get_avg_playtime() }}">
							{{ game.get_avg_playtime()|duration_format }}
						</td>
					</tr>
				{% endfor %}
			</tbody>

			{% endif %}

			{% if content_type == "plays" %}
			<thead>
				<tr>
					<th data-sorted="true" data-sorted-direction="descending">Date</th>
					<th>Name</th>
					<th>Play Time</th>
					<th>Players</th>
					<th>Winner(s)</th>
				</tr>
			</thead>
			<tbody>
				{% for play in content %}
					<tr>
						<td><a href="{{ url('play', play_id=play.id) }}">{{ play.date }}</a></td>
						<td><a href="{{ url('game', game_id=play.game.id) }}">{{ play.game.name }}</a></td>
						<td data-value="{{ play.play_time }}">
							{{ play.play_time|duration_format }}
						</td>
						<td>{{ play.num_players }}</td>
						<td>
							{% set first = 1 %}
							{% for playstat in play.playstat_set.all() %}
								{% if playstat.stat.name ==  'Won'  and playstat.value == 'T'  and first == 1 %}
									{% set first = first - 1 %}
									<a href="{{ url('player', playstat.player.id) }}">{{ playstat.player.username }}</a>
								{% elif playstat.stat.name ==  'Won'  and playstat.value == 'T'  and first == 0 %}
									, <a href="{{ url('player', playstat.player.id) }}">{{ playstat.player.username }}</a>
								{% endif %}
							{% endfor %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
			{% endif %}

			{% if content_type == "players" %}
			<thead>
				<tr>
					<th data-sorted="true" data-sorted-direction="ascending">Name</th>
					<th>Plays</th>
					<th>Wins</th>
					<th>Total Play Time</th>
					<th>Game Points</th>
					<th>Most Recent Play</th>
				</tr>
			</thead>
			<tbody>
				{% for player in content %}
					{% if not player.username == 'game' %}
					<tr>
						<td><a href="{{ url('player', player_id=player.id) }}">{{ player.username }}</a></td>
						<td>{{ player.playstat_set.all().filter(stat__name = 'Won').count()}}</td>
						<td>{{ player.playstat_set.all().filter(value='T', stat__name = 'Won').count()}}</td>
						<td data-value="{{ plays.filter(playstat__player=player).distinct()|sum(attribute='play_time') }}">
							{{ plays.filter(playstat__player=player).distinct()|sum(attribute='play_time')|duration_format}}
						</td>
						<td>
						{% set points = 0 %}
						{% for stat in player.playstat_set.all().filter(value='T', stat__name = 'Won') %}
							{% set points = points + stat.play.game.weight %}
							{% if loop.last %}
								{{ points|round(2) }}
							{% endif %}
						{% endfor %}
						</td>
							{% for play in plays.filter(playstat__player=player).distinct().order_by('-date', 'id')[:1] %}
							<td data-value="{{ play.date }}">
									<a href="{{ url('play', play_id=play.id) }}">{{ play.game }} - {{ play.date.strftime('%B %d, %Y') }}</a>
							</td>
							{% endfor %}
					</tr>
					{% endif %}
				{% endfor %}
			</tbody>
			{% endif %}
		</table>
		
		<p>{{ content.count() }} {{ content_type|title }}</p>

		<p class="centered">@TODO Add pager here</p>
		
	</div>
{% endblock %}

gamestats/templates/game_base.jinja
{% extends "base.jinja" %}
{% block title %}{{ game.name }}{% endblock %}
{% block css %}main.css{% endblock %}

{% block content %}
	<div class="page-title grid-100">
		<h2>{{ game.name }}</h2>
	</div>
	<div id="stats" class="clearfix">
		<div id="game-cover" class="grid-30">
			<img src="{{ game.image }}" title="{{ game.name }}" />
		</div>
		<div class="grid-70 color-green box">
			<h3>Stats</h3>
			<ul>
				<li><strong>BGG Rating:</strong> {{ game.bgg_bayesaverage }}</li>
				<li><strong>Plays:</strong> {{ plays.count() }}</li>
				<li><strong>Average Play Time:</strong> {{ avg_playtime['play_time__avg']| duration_format }}</li>
				<li><strong>Suggested Play Time:</strong> {{ game.bgg_playing_time| duration_format }}</li>
				<li><strong>Players:</strong> {{ game.min_players }}-{{ game.max_players }}</li>
			</ul>
		</div>
		<div class="grid-70 color-purple box right">
			<h3>Who's played it?</h3>
			<ul>
			{% for player in players_who_have_played %}
				<li><a href="{{ url('player', player_id=player.id) }}">{{ player }}</a></li>
			{% endfor %}
			</ul>
		</div>
	</div>

	<div id="description" class="grid-100">
		<h3>Description</h3>
		<p>{{ game.description|safe }}</p>
		{% block gamestats %}{% endblock %}
	</div>
	<div id="plays" class="grid-100">
		<h3>Recent Plays</h3>
		<table>
			<thead>
				<tr>
					<th>Date</th>
					<th>Play Time</th>
					<th># of Players</th>
					<th>Expansions</th>
				</tr>
			</thead>
			<tbody>
				{% for play in plays %}
					<tr>
						<td><a href="{{ url('play', play_id=play.id) }}">{{ play.date }}</a></td>
						<td>{{ play.play_time| duration_format }}</td>
						<td>{{ play.num_players }}</td>
						<td>{% for expansion in play.expansions.all() %} {{expansion}}{% endfor %}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

gamestats/templates/game_list.jinja
{% extends "base.jinja" %}
{% block title %}Wins by categories{% endblock %}
{% block css %}main.css{% endblock %}
{% block extraHead %}
	<script type="text/javascript" src="{{ static('javascript/sortable.min.js') }}"></script> 
{% endblock %}
{% block content %}
	<div class="page-title grid-100">
		<h2>{{ title }}</h2>
	</div>
	<div class="grid-100">
		<ol>
			{% for game in games %}
				<li><a href="{{ url('game', game_id=game.id) }}">{{ game.name }}</a></li>
			{% endfor %}
		</ol>
	</div>
{% endblock %}